run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - errorlint
    - exhaustive

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Struct field reordering for alignment is a micro-optimization
      - shadow           # Variable shadowing is idiomatic in Go (e.g. if err := ...)
      - unusedwrite      # False positives on struct initialization in tests
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: raven
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gosec:
    excludes:
      - G104  # Unhandled errors (errcheck covers this)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam
    - path: mock
      linters:
        - unused
  max-issues-per-linter: 50
  max-same-issues: 10
